# Costmap Layering config
# Detail on each costmap layer goes here!
local_costmap:

  # Layer 1 - Static
  static_layer:
    enabled:              true

  # Layer 2 - Obstacle
  obstacle_layer:
    enabled:              true
    origin_z:             0.0
    max_obstacle_height:  1.5   # Max Obstacle
    z_resolution:         0.3   # Resolution
    z_voxels:             5     # max_obstacle_height = z_resolution * z_voxel
    unknown_threshold:    15
    mark_threshold:       0
    combination_method:   1
    track_unknown_space:  false # True needed for disabling global path planning through unknown space
    obstacle_range:       2.0
    raytrace_range:       2.1
    publish_voxel_map:    false
    observation_sources:  lidar_scan

    # Observation Sources detail here
    lidar_scan:
      data_type:          LaserScan # From Sensor msgs
      sensor_frame:       lidar
      topic:              scan
      marking:            true
      clearing:           true
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0
      inf_is_valid:        true
      observation_persistence: 0.0  #Secs

  # Layer 3 - Inflation
  inflation_layer:
    enabled:              true
    cost_scaling_factor:  3.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     1.5 # max. distance from an obstacle at which costs are incurred for planning paths.
